---
name: Lingua-Any-Numbers
version: 0.26
author:
  - 'Burak Gursoy <burak@cpan.org>'
abstract: Converts numbers into (any available language) string.
license: perl
resources:
  license: http://dev.perl.org/licenses/
  repository: http://bitbucket.org/burak/cpan-lingua-any-numbers/
requires:
  I18N::LangTags: 0.35
  Lingua::EN::Numbers: 0
  Win32::Locale: 0
build_requires:
  Test::More: 0.40
recommends:
  Task::Lingua::Any::Numbers: 0.11
provides:
  Lingua::Any::Numbers:
    file: lib/Lingua/Any/Numbers.pm
    version: 0.26
no_index:
  directory:
    - tools
    - t
generated_by: Module::Build version 0.32
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.2.html
  version: 1.2
