---
name: Lingua-Any-Numbers
version: 0.30
author:
  - 'Burak Gursoy <burak@cpan.org>'
abstract: Converts numbers into (any available language) string.
license: perl
resources:
  license: http://dev.perl.org/licenses/
  repository: http://bitbucket.org/burak/cpan-lingua-any-numbers/
requires:
  I18N::LangTags::Detect: 0
  Lingua::EN::Numbers: 0
build_requires:
  Test::More: 0.40
provides:
  Lingua::Any::Numbers:
    file: lib/Lingua/Any/Numbers.pm
    version: 0.30
no_index:
  directory:
    - monolithic_version
    - builder
    - t
generated_by: Module::Build version 0.32
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.2.html
  version: 1.2
